### ISSUE TITLE
Check why Relayer Invalid Tx Cleanup script doesn't work

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/plumbing#8]
https://github.com/CirclesUBI/plumbing/tree/main/relayer-invalid-tx

Why it doesn't delete the db entries?

**Comment by juanenrisley** [comment]
The functionality is fine. The problem was that the methods that are being call for getting the info of the transaction do not exist:

https://github.com/CirclesUBI/plumbing/blob/9c4bfb2f5cf024492b2a833806f5cf9bea660695/relayer-invalid-tx/analyze.py#L64
https://github.com/CirclesUBI/plumbing/blob/9c4bfb2f5cf024492b2a833806f5cf9bea660695/relayer-invalid-tx/analyze.py#L65

Instead of `w3.eth.getTransactionReceipt` and `w3.eth.getBlock` we need to use  `w3.eth.get_transaction_receipt` and  `w3.eth.get_block`.
